spring.application.name=http-service
#
spring.datasource.url=jdbc:postgresql://localhost/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
#
spring.datasource.connection-fetch=lazy
#
spring.threads.virtual.enabled=true
#
spring.elasticsearch.uris=http://localhost:9200
