spring.application.name=customers
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.url=jdbc:postgresql://localhost/mydatabase
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*
server.tomcat.threads.max=10
spring.threads.virtual.enabled=true
spring.ai.ollama.chat.model=gemma4:26b